source "https://rubygems.org"
gem "jekyll"  "~> 4.3"

gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-theme-primer" 
gem "jekyll-github-metadata" 

gem "jekyll-coffeescript" 
gem "jekyll-commonmark-ghpages"
gem "jekyll-gist" 
gem "jekyll-github-metadata"
gem "jekyll-paginate" 
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter" 
gem "jekyll-readme-index" 
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings" 
gem "jekyll-remote-theme"